server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.29.54:3306/cms?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: gaoxy
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

 #       naming:
 #          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
